# Generated by Django 3.2.4 on 2021-06-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='song',
            name='start_point',
            field=models.IntegerField(default=0),
        ),
    ]
