# Generated by Django 3.2.4 on 2021-06-06 17:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_start', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('game_started', models.BooleanField(default=False)),
                ('round_no', models.IntegerField(default=0)),
                ('title_weight', models.FloatField(default=0.5)),
                ('author_weight', models.FloatField(default=0.5)),
                ('source_weight', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=128)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_server_api.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('last_answer', models.CharField(max_length=128)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_server_api.game')),
            ],
        ),
    ]
