# Generated by Django 3.2.4 on 2021-06-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_server_api', '0002_alter_song_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_answer',
            field=models.CharField(default='', max_length=128),
        ),
    ]
