# Generated by Django 3.2.4 on 2021-06-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_server_api', '0005_song_round_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='round_no',
            field=models.IntegerField(default=0),
        ),
    ]
