# Generated by Django 3.2.4 on 2021-06-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_server_api', '0006_player_round_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round_ended',
            field=models.BooleanField(default=False),
        ),
    ]
