# Generated by Django 3.2.4 on 2021-06-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_server_api', '0007_game_round_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_ended',
            field=models.BooleanField(default=False),
        ),
    ]
