version: "3.9"
   
services:
  db:
      image: mysql:5.7.22
      restart: always
      environment:
        MYSQL_DATABASE: songs
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - .dbdata:/var/lib/mysql
      ports:
        - 33066:3306
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db